// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkltvmkhwarniihfbzyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprbHR2bWtod2FybmlpaGZienl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjcyMzYsImV4cCI6MjA2MzkwMzIzNn0.KpPQyWDfSEtiwVx1Edbpet25YK0GPuZFrxTYvMw3qIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);